#!/usr/bin/env bash
# This script displays a list of all currently running processes, for all users,
# in a user-oriented format with a process hierarchy.

ps -e -o user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command --forest
