#!/usr/bin/env bash
# This script displays numbers from 1 to 20 with specific messages for certain numbers.

number=1

while [ $number -le 20 ]; do
    case $number in
        4)
            echo "$number"
            echo "bad luck from China"
            ;;
        9)
            echo "$number"
            echo "bad luck from Japan"
            ;;
        17)
            echo "$number"
            echo "bad luck from Italy"
            ;;
        *)
            echo "$number"
            ;;
    esac
    ((number++))
done
